{{- if and .Values.tls.caCert (not .Values.tls.existingCaSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "observer.fullname" . }}-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.tls.caSecretKey }}: |
    {{- .Values.tls.caCert | nindent 4 }}
{{- end }}
{{- if and .Values.webhook.caCert (not .Values.webhook.existingCaSecret) (eq (include "observer.hasWebhookActuator" .) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "observer.fullname" . }}-webhook-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.webhook.caSecretKey }}: |
    {{- .Values.webhook.caCert | nindent 4 }}
{{- end }}
