{{- if eq (include "observer.createsSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "observer.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.couchbase.existingSecret }}
  {{ .Values.couchbase.usernameKey }}: {{ .Values.couchbase.username | quote }}
  {{ .Values.couchbase.passwordKey }}: {{ .Values.couchbase.password | quote }}
  {{- end }}
  {{- if and (eq (include "observer.hasWebhookActuator" .) "true") (not .Values.webhook.existingSecret) }}
  {{- with .Values.webhook.username }}
  webhook-username: {{ . | quote }}
  {{- end }}
  {{- with .Values.webhook.password }}
  webhook-password: {{ . | quote }}
  {{- end }}
  {{- end }}
{{- end }}
